version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: classic_rock
    ports:
      - '5432:5432'
  apple_challenge:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: docker-dev
    ports:
      - '3000:3000'